# Generated by Django 4.1 on 2025-03-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(),
        ),
    ]
