# Generated by Django 4.2 on 2025-05-12 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import posts.helpers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostMetaKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_key", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "Post Meta Key",
                "db_table": "post_meta_key",
            },
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=255, unique=True)),
                (
                    "post_slug",
                    models.SlugField(default=None, max_length=255, unique=True),
                ),
                ("post_content", tinymce.models.HTMLField(blank=True)),
                ("post_excerpt", models.TextField(blank=True)),
                (
                    "post_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[("post", "Post"), ("page", "Page"), ("menu", "Menu")],
                        default=0,
                        max_length=20,
                    ),
                ),
                ("post_date", models.DateTimeField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "post_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=posts.helpers.get_file_path
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="This is the page title, that appers in the title bar.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "seo_keyword",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for search engines.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True,
                        help_text="A short description, displayed in search results.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "og_description",
                    models.TextField(blank=True, max_length=255, unique=True),
                ),
                (
                    "post_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="posts.posts",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts",
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostMetaValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_value", models.TextField()),
                ("meta_id", models.ManyToManyField(to="posts.postmetakey")),
            ],
            options={
                "verbose_name_plural": "Post Meta Values",
                "db_table": "post_meta_values",
            },
        ),
        migrations.AddField(
            model_name="postmetakey",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="posts.posts"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postmetakey",
            unique_together={("post_id", "meta_key")},
        ),
    ]
